version: '3.3'

services:
  db:
    container_name: venkatma_mysql
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: 'customer'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33066:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

  customer:
    container_name: venkatma_php
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
    depends_on:
      - db
    links:
      - db
    volumes:
      - ../:/var/www/html

volumes:
  db:
